<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260912234505 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Users, scores and the PdoSessionHandler sessions table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE scores (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, points INT NOT NULL, lines INT NOT NULL, level INT NOT NULL, achieved_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX scores_user_points_idx ON scores (user_id, points)');
        $this->addSql('CREATE INDEX scores_points_idx ON scores (points)');
        $this->addSql('CREATE INDEX IDX_750375EA76ED395 ON scores (user_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(20) NOT NULL, username_canonical VARCHAR(20) NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E992FC23A8 ON users (username_canonical)');
        $this->addSql('ALTER TABLE scores ADD CONSTRAINT FK_750375EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Schema expected by Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler (pgsql).
        $this->addSql('CREATE TABLE sessions (sess_id VARCHAR(128) NOT NULL PRIMARY KEY, sess_data BYTEA NOT NULL, sess_lifetime INTEGER NOT NULL, sess_time INTEGER NOT NULL)');
        $this->addSql('CREATE INDEX sessions_sess_lifetime_idx ON sessions (sess_lifetime)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sessions');
        $this->addSql('ALTER TABLE scores DROP CONSTRAINT FK_750375EA76ED395');
        $this->addSql('DROP TABLE scores');
        $this->addSql('DROP TABLE users');
    }
}
